### PR TITLE
Some verbosity in the mediainfo access/exec errors

### PR DESCRIPTION
**Pull request by Tontonitch**
Some verbosity in the mediainfo access/exec errors

### CODE REVIEW

**Comment by xbgmsharp** [comment]
Not a good idea for production system to output. The documentation refer to the command you should run to test your system.

**Comment by Tontonitch** [comment]
ok, but for when I test the command it is ok, and when I use piwigo it is not.

This small change gives me some clues, which is useful:

```
Mediainfo error reading file. Is MediaInfo install? Is MediaInfo in path?
Is the video accessible & readable, Try to run the command manually.
../usr/bin/mediainfo --Full --Output=XML --Language=raw './upload/2018/04/02/20180402224214-0193f859.mp4'
output: ../usr/bin/mediainfo: error while loading shared libraries: libmediainfo.so.0: cannot open shared object file: No such file or directory
```

**Comment by Tontonitch** [comment]
For your info: I had set the LD_LIBRARY_PATH environment variable in mediainfo.php:

```
try {
putenv('LANG=en_US.UTF-8');
putenv('LD_LIBRARY_PATH=xxxxxxxxxxxx);
```

That's the only way I found. Now it works.

So I would say that if the change of this pull request helped me to figure out what was the issue, maybe it can be useful for somebody else.

What do you think?

**Comment by xbgmsharp** [comment]
You should run the command from a shell directly. No need to add more verbosity from the production command line.

**Pull request merged**
