### PR TITLE
Add .mov extension

### PR DESCRIPTION
**Pull request by endrepavel**
Add .mov extension

### CODE REVIEW

**Comment by Cheatha** [comment]
I'd love to see this commit merged!

**Comment by brentkearney** [comment]
Me too!

**Comment by Phil353556** [comment]
+1

**Comment by EddyLB** [comment]
For a number of reasons, see for example [here](https://en.wikipedia.org/wiki/HTML_video#Browser_support) and [here](https://caniuse.com/?search=video), this format is not managed by web browsers. So we believe that allowing users to upload .mov files would not be a good idea because they won't be able to watch them with most browsers.

**Pull request closed without merging**
